package view;

import controller.Constantes;
import controller.FileUtils;
import model.*;

import java.io.Serial;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author hol
 */
public class Admin_1_usuario extends javax.swing.JFrame {

    @Serial
    private static final long serialVersionUID = 5497595562617462243L;

    public void rellenarDatos(String correo) {
        // leer el archivo de usuarios
        ArrayList<UsuarioBase> usuarioBase = (ArrayList<UsuarioBase>) FileUtils.readFromFile(Constantes.PATH_USERS);
        // buscar el usuario
        UsuarioBase usuario = null;
        for (UsuarioBase u : usuarioBase) {
            if (u.getCorreo().equals(correo)) {
                usuario = u;
                break;
            }
        }

        // Inicializamos el cliente, ya sea particular o empresa
        ClienteBase cliente;

        // Si se seleccionó ClienteParticular. Rellenamos los campos específicos de esa clase
        if (usuario.getRol() == UsuarioBase.Rol.Particular) {
            cliente = (ClienteParticular) usuario;
            Rellenar_DniCif.setText(((ClienteParticular) cliente).getDni());
            jLabelWeb.setVisible(false);
            Rellenar_Web.setVisible(false);
        } else {
            // Si no se seleccionó ClienteParticular, asumimos que es ClienteEmpresa. Rellenamos los campos específicos de esa clase
            cliente = (ClienteEmpresa) usuario;
            jLabelDniCif.setText("CIF");
            Rellenar_DniCif.setText(((ClienteEmpresa) cliente).getCIF());
            Rellenar_Web.setText(((ClienteEmpresa) cliente).getWeb());
        }

        // Configuramos los campos comunes entre ClienteParticular y ClienteEmpresa
        Rellenar_Nombre.setText(cliente.getNombre());
        Rellenar_Telefono.setText(String.valueOf(cliente.getTelefono()));
        Rellenar_Correo.setText(usuario.getCorreo());
        Rellenar_Contrasena.setText(usuario.getContrasena());
        Rellenar_Calle.setText(cliente.getDireccion().getCalle());
        Rellenar_Numero.setText(String.valueOf(cliente.getDireccion().getNumero()));
        Rellenar_CP.setText(String.valueOf(cliente.getDireccion().getCodigoPostal()));
        Rellenar_Ciudad.setText(cliente.getDireccion().getCiudad());
        Rellenar_Tarjeta.setText(cliente.getTarjeta().getNumero16());
        //convertir date a string
        Date date = cliente.getTarjeta().getCaduca();
        String strDate = DateFormat.getDateInstance().format(date);
        Rellenar_Caducidad.setText(strDate);
    }
    /**
     * Creates new form Elección_de_cliente
     */
    public Admin_1_usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Registro = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        Clave = new javax.swing.JLabel();
        Rellenar_Correo = new javax.swing.JTextField();
        Rellenar_Telefono = new javax.swing.JTextField();
        Rellenar_Nombre = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();
        jLabelDniCif = new javax.swing.JLabel();
        Rellenar_DniCif = new javax.swing.JTextField();
        jLabelWeb = new javax.swing.JLabel();
        Rellenar_Caducidad = new javax.swing.JTextField();
        Calle = new javax.swing.JLabel();
        Numero = new javax.swing.JLabel();
        CP = new javax.swing.JLabel();
        Ciudad = new javax.swing.JLabel();
        Tarjeta = new javax.swing.JLabel();
        Rellenar_CP = new javax.swing.JTextField();
        Rellenar_Numero = new javax.swing.JTextField();
        Rellenar_Calle = new javax.swing.JTextField();
        Caducidad = new javax.swing.JLabel();
        Rellenar_Ciudad = new javax.swing.JTextField();
        Rellenar_Tarjeta = new javax.swing.JTextField();
        Rellenar_Web = new javax.swing.JTextField();
        Rellenar_Contrasena = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Registro.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Registro.setText("Información Usuario");
        Registro.setToolTipText("");

        Nombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Nombre.setText("Nombre: ");

        Telefono.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Telefono.setText("Telefono:");

        Correo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Correo.setText("Correo:");

        Clave.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Clave.setText("Contraseña:");

        Rellenar_Correo.setEditable(false);
        Rellenar_Correo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Rellenar_Telefono.setEditable(false);
        Rellenar_Telefono.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Rellenar_Nombre.setEditable(false);
        Rellenar_Nombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButtonBack.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonBack.setText("Atrás");
        jButtonBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelDniCif.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelDniCif.setText("DNI:");

        Rellenar_DniCif.setEditable(false);
        Rellenar_DniCif.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelWeb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelWeb.setText("Web:");

        Rellenar_Caducidad.setEditable(false);
        Rellenar_Caducidad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Calle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Calle.setText("Calle:");

        Numero.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Numero.setText("Número:");

        CP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CP.setText("CP:");

        Ciudad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Ciudad.setText("Ciudad:");

        Tarjeta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Tarjeta.setText("Tarjeta");

        Rellenar_CP.setEditable(false);
        Rellenar_CP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Rellenar_Numero.setEditable(false);
        Rellenar_Numero.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Rellenar_Calle.setEditable(false);
        Rellenar_Calle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Caducidad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Caducidad.setText("Caducidad:");

        Rellenar_Ciudad.setEditable(false);
        Rellenar_Ciudad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Rellenar_Tarjeta.setEditable(false);
        Rellenar_Tarjeta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Rellenar_Web.setEditable(false);
        Rellenar_Web.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Rellenar_Contrasena.setEditable(false);
        Rellenar_Contrasena.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Calle, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Caducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Rellenar_Calle, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(Rellenar_CP)
                                    .addComponent(Rellenar_Caducidad)
                                    .addComponent(Rellenar_Ciudad)
                                    .addComponent(Rellenar_Tarjeta)
                                    .addComponent(Rellenar_Numero)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelWeb)
                                    .addComponent(jLabelDniCif))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Rellenar_Correo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(Rellenar_Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rellenar_DniCif, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rellenar_Web, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rellenar_Telefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rellenar_Contrasena)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rellenar_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rellenar_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rellenar_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clave)
                    .addComponent(Rellenar_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rellenar_Calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rellenar_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rellenar_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ciudad)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tarjeta)
                            .addComponent(Rellenar_Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Rellenar_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caducidad)
                    .addComponent(Rellenar_Caducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rellenar_DniCif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDniCif))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWeb)
                    .addComponent(Rellenar_Web, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        Admin_1_usuarios admin1Usuarios = new Admin_1_usuarios();
        admin1Usuarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_1_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_1_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_1_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_1_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin_1_usuario registro = new Admin_1_usuario();
                registro.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CP;
    private javax.swing.JLabel Caducidad;
    private javax.swing.JLabel Calle;
    private javax.swing.JLabel Ciudad;
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Numero;
    private javax.swing.JLabel Registro;
    private javax.swing.JTextField Rellenar_CP;
    private javax.swing.JTextField Rellenar_Caducidad;
    private javax.swing.JTextField Rellenar_Calle;
    private javax.swing.JTextField Rellenar_Ciudad;
    private javax.swing.JTextField Rellenar_Contrasena;
    private javax.swing.JTextField Rellenar_Correo;
    private javax.swing.JTextField Rellenar_DniCif;
    private javax.swing.JTextField Rellenar_Nombre;
    private javax.swing.JTextField Rellenar_Numero;
    private javax.swing.JTextField Rellenar_Tarjeta;
    private javax.swing.JTextField Rellenar_Telefono;
    private javax.swing.JTextField Rellenar_Web;
    private javax.swing.JLabel Tarjeta;
    private javax.swing.JLabel Telefono;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabelDniCif;
    private javax.swing.JLabel jLabelWeb;
    // End of variables declaration//GEN-END:variables
}
