package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import controller.Constantes;
import controller.FileUtils;
import model.UsuarioBase;

import javax.swing.*;
import java.io.Serial;
import java.util.ArrayList;

/**
 * @author hol
 */
public class ChangePassword extends javax.swing.JFrame {

    @Serial
    private static final long serialVersionUID = -1237743494669255452L;

    /**
     * Creates new form Olvidar_Contraseña
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelContrasenaAntigua = new javax.swing.JLabel();
        jButtonChange = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldContrasenaAntigua = new javax.swing.JPasswordField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jPasswordFieldContrasenaNueva = new javax.swing.JPasswordField();
        jLabelContrasenaNueva = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBack.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonBack.setText("Atrás");
        jButtonBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelCorreo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelCorreo.setText("Correo:");

        jLabelContrasenaAntigua.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelContrasenaAntigua.setText("Contraseña Antigua:");

        jButtonChange.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButtonChange.setText("Cambiar");
        jButtonChange.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jButtonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("CAMBIAR CONTRASEÑA");

        jPasswordFieldContrasenaAntigua.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTextFieldCorreo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPasswordFieldContrasenaNueva.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabelContrasenaNueva.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelContrasenaNueva.setText("Contraseña Nueva:");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logominiEAT.png"))); // NOI18N
        jLabelLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelContrasenaNueva)
                                    .addComponent(jLabelContrasenaAntigua)
                                    .addComponent(jLabelCorreo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCorreo)
                                    .addComponent(jPasswordFieldContrasenaAntigua)
                                    .addComponent(jPasswordFieldContrasenaNueva, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(141, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabelLogo)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonChange, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCorreo)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelContrasenaAntigua)
                            .addComponent(jPasswordFieldContrasenaAntigua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelContrasenaNueva)
                            .addComponent(jPasswordFieldContrasenaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonChange)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLogo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeActionPerformed
        if (jTextFieldCorreo.getText().equals("") || String.valueOf(jPasswordFieldContrasenaAntigua.getPassword()).equals("") || String.valueOf(jPasswordFieldContrasenaNueva.getPassword()).equals("")) {
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacios");
        } else {
            // contraseñas iguales
            if (String.valueOf(jPasswordFieldContrasenaAntigua.getPassword()).equals(String.valueOf(jPasswordFieldContrasenaNueva.getPassword()))) {
                JOptionPane.showMessageDialog(null, "La contraseña nueva no puede ser igual a la antigua");
            } else {
                FileUtils file = new FileUtils();
                ArrayList<UsuarioBase> usuarios;
                // Leemos el contenido del fichero
                usuarios = (ArrayList<UsuarioBase>) file.readFromFile(Constantes.PATH_USERS);
                //Buscamos el usuario
                boolean encontrado = false;
                for (UsuarioBase usuario : usuarios) {
                    if (usuario.getCorreo().equals(jTextFieldCorreo.getText())) { // Si existe un usuario con ese correo
                        encontrado = true;
                        // Comprobamos que la contraseña antigua es correcta
                        if (usuario.getContrasena().equals(String.valueOf(jPasswordFieldContrasenaAntigua.getPassword()))) {
                            // Cambiamos la contraseña
                            usuario.setContrasena( String.valueOf(jPasswordFieldContrasenaNueva.getPassword()));
                            // Escribimos la lista de usuarios actualizada al fichero
                            file.writeToFile(Constantes.PATH_USERS, usuarios);
                            Login login = new Login();
                            login.setVisible(true);
                            this.setVisible(false);
                            JOptionPane.showMessageDialog(null, "Contraseña cambiada correctamente");
                        } else {
                            JOptionPane.showMessageDialog(null, "La contraseña antigua no es correcta");
                        }
                    }
                }
                // Si no existe un usuario con ese correo
                if (!encontrado) {
                    JOptionPane.showMessageDialog(null, "No existe un usuario con ese correo");
                }
            }
        }
    }//GEN-LAST:event_jButtonChangeActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        Login i = new Login();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonChange;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelContrasenaAntigua;
    private javax.swing.JLabel jLabelContrasenaNueva;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPasswordField jPasswordFieldContrasenaAntigua;
    private javax.swing.JPasswordField jPasswordFieldContrasenaNueva;
    private javax.swing.JTextField jTextFieldCorreo;
    // End of variables declaration//GEN-END:variables
}
