package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import controller.Constantes;
import controller.FileUtils;
import model.UsuarioBase;

import javax.swing.*;
import java.io.Serial;
import java.util.ArrayList;

/**
 * @author hol
 */
public class Login extends javax.swing.JFrame {

    @Serial
    private static final long serialVersionUID = 2379313079115426828L;

    /**
     * Creates new form Inicio
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Correo = new javax.swing.JLabel();
        Clave = new javax.swing.JLabel();
        Texto_Correo = new javax.swing.JTextField();
        Boton_Entrar = new javax.swing.JButton();
        No_tienes_cuenta = new javax.swing.JLabel();
        Registrarse = new javax.swing.JButton();
        Contrasena = new javax.swing.JPasswordField();
        Cambiar_Contrasena = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Correo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Correo.setText("Correo:");

        Clave.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Clave.setText("Contraseña:");

        Texto_Correo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Texto_Correo.setNextFocusableComponent(Contrasena);

        Boton_Entrar.setBackground(new java.awt.Color(184, 234, 185));
        Boton_Entrar.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        Boton_Entrar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Entrar.setText("Entrar");
        Boton_Entrar.setAlignmentY(0.1F);
        Boton_Entrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Boton_Entrar.setNextFocusableComponent(Registrarse);
        Boton_Entrar.setOpaque(true);
        Boton_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_EntrarActionPerformed(evt);
            }
        });

        No_tienes_cuenta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        No_tienes_cuenta.setText("¿No tienes cuenta?");

        Registrarse.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Registrarse.setText("Registrarse");
        Registrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Registrarse.setNextFocusableComponent(Cambiar_Contrasena);
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });

        Contrasena.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Contrasena.setNextFocusableComponent(Boton_Entrar);

        Cambiar_Contrasena.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cambiar_Contrasena.setText("Cambia contraseña");
        Cambiar_Contrasena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        Cambiar_Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cambiar_ContrasenaActionPerformed(evt);
            }
        });

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logominiEAT.png"))); // NOI18N
        jLabelLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CARLOS MARICON");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(No_tienes_cuenta)
                                .addGap(18, 18, 18)
                                .addComponent(Registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Cambiar_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Correo)
                            .addComponent(Clave))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Texto_Correo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Contrasena))
                                .addGap(18, 18, 18)
                                .addComponent(Boton_Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(42, 42, 42)
                .addComponent(jLabelLogo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Boton_Entrar)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Texto_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Clave)
                            .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(No_tienes_cuenta)
                    .addComponent(Registrarse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cambiar_Contrasena)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cambiar_ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cambiar_ContrasenaActionPerformed
        ChangePassword changePassword = new ChangePassword();
        changePassword.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Cambiar_ContrasenaActionPerformed

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
        Registro i = new Registro();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void Boton_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_EntrarActionPerformed
        if (Texto_Correo.getText().equals("") || Contrasena.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese todos los datos");
        } else {
            String correo = Texto_Correo.getText();
            String clave = String.valueOf(Contrasena.getPassword());
            FileUtils file = new FileUtils();
            ArrayList<UsuarioBase> usuarios;
            // leer usuarios desde fichero users.txt y deserializar en ArrayList
            usuarios = (ArrayList<UsuarioBase>) file.readFromFile(Constantes.PATH_USERS);
            // buscar usuario en ArrayList
            for (UsuarioBase usuario : usuarios) {
                if (usuario.getCorreo().equals(correo) && usuario.getContrasena().equals(clave)) {
                    // Guardamos el usuario en la clase estatica
                    Constantes.USUARIO_ACTUAL = usuario;
                    if (usuario.getRol() == UsuarioBase.Rol.Administrador) {
                        Admin_1 admin1 = new Admin_1();
                        admin1.setVisible(true);
                        this.setVisible(false);
                    } else {
                        SearchRestaurant searchRestaurant = new SearchRestaurant();
                        searchRestaurant.setVisible(true);
                        this.setVisible(false);
                    }
                    break;
                }
            }
            if (Constantes.USUARIO_ACTUAL == null) {
                JOptionPane.showMessageDialog(null, "Datos incorrectos");
            }
        }
    }//GEN-LAST:event_Boton_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Entrar;
    private javax.swing.JButton Cambiar_Contrasena;
    private javax.swing.JLabel Clave;
    private javax.swing.JPasswordField Contrasena;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel No_tienes_cuenta;
    private javax.swing.JButton Registrarse;
    private javax.swing.JTextField Texto_Correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
